version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/node-bot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/windows-launcher"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/plugins/obsidian-plugin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "nuget"
    directory: "/windows-native-launcher"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
