// #1387: which remembered entities get a note in her vault's Views/. Uses
// what the store already knows -- the entity types the classifier wrote
// (not_an_entity, canonical aliases) -- plus one rule for candidates it
// hasn't typed yet. Every exclusion says why.

// English filler that capitalised sentence starts turn into "entities"
// ("And", "Because", "Actually"). Only applied to untyped candidates: a
// typed entity named like one ("May", a person) always stays.
const FILLER = new Set(
  (
    "and but or so because actually also anyway then just well maybe really yeah yep nope hmm hm oh ah um uh " +
    "like right sure honestly basically literally still though although if while since after before now today " +
    "tomorrow yesterday here there everything something nothing anything someone everyone hey hi hello sorry " +
    "thank thanks please ok okay yes no not let lets wait btw also"
  ).split(" "),
);
const MIN_UNTYPED_MENTIONS = 2;

// entityIndex: { key: [{ display, sessionId, at }] }; types: the store's
// entity-types.json ({ key: { type, canonicalKey? } }).
// Returns { entities: { key: { display, type, mentions } }, excluded: [{ key, why }] }.
function visibleEntities(entityIndex = {}, types = {}) {
  const entities = {};
  const excluded = [];
  const canonicalOf = (key) => {
    const seen = new Set();
    let k = key;
    while (types[k]?.canonicalKey && !seen.has(k)) {
      seen.add(k);
      k = types[k].canonicalKey;
    }
    return k;
  };
  for (const [key, mentions] of Object.entries(entityIndex)) {
    if (!Array.isArray(mentions) || !mentions.length) continue;
    const canonical = canonicalOf(key);
    const type = types[canonical]?.type || types[key]?.type || null;
    if (type === "not_an_entity") {
      excluded.push({ key, why: "classified as not an entity" });
      continue;
    }
    if (canonical !== key) excluded.push({ key, why: `alias of ${canonical}` });
    const entry = (entities[canonical] ||= { display: null, type, mentions: [] });
    entry.mentions.push(...mentions);
    if (canonical === key || !entry.display) entry.display = mentions[mentions.length - 1].display || key;
  }
  // Untyped candidates: filler words never, single words only once seen twice.
  for (const [key, e] of Object.entries(entities)) {
    if (e.type) continue;
    const singleWord = !/\s/.test(key.trim());
    if (singleWord && FILLER.has(key.toLowerCase())) excluded.push({ key, why: "untyped filler word" });
    else if (singleWord && e.mentions.length < MIN_UNTYPED_MENTIONS) excluded.push({ key, why: `untyped single word mentioned ${e.mentions.length} time` });
    else continue;
    delete entities[key];
  }
  for (const e of Object.values(entities)) e.mentions.sort((a, b) => String(a.at || "").localeCompare(String(b.at || "")));
  return { entities, excluded };
}


// #1388: the three index views. Sorted and without dates, so a refresh with
// nothing new rewrites nothing. Links go only to notes the sync or
// buildMemoryNotes write (Facts/..., Facts/Pending/..., Views/Entities/...).
const { noteName, statusOf } = require("./memory-vault");
const { ENTITY_TYPES } = require("./entity-ontology");

const TYPE_HEADINGS = { person: "People", place: "Places", object: "Objects", organization: "Organizations", event: "Events", preference: "Preferences", media: "Media" };

// One line, nothing that breaks [[target|label]].
const label = (text) => String(text).replace(/[\[\]|\r\n\s]+/g, " ").trim();
const byText = (a, b) => (a < b ? -1 : a > b ? 1 : 0);
const sortKeys = (keys) => keys.sort((a, b) => byText(a.toLowerCase(), b.toLowerCase()) || byText(a, b));

function buildFactsIndex(facts = []) {
  const keys = sortKeys(facts.filter((f) => statusOf(f) === "active").map((f) => f.key));
  return [
    "# Facts Index",
    "",
    `Active facts: ${keys.length}. Generated by Mana; edits here are overwritten.`,
    "",
    ...(keys.length ? keys.map((k) => `- [[Facts/${noteName(k)}|${label(k)}]]`) : ["_(none yet)_"]),
    "",
  ].join("\n");
}

function buildPendingReview(facts = []) {
  const pending = facts.filter((f) => statusOf(f) === "pending");
  const byKey = new Map(pending.map((f) => [f.key, f]));
  return [
    "# Pending Review",
    "",
    `Facts waiting for approval: ${byKey.size}. A link here never approves anything; approve a fact where you do today.`,
    "",
    ...(byKey.size ? sortKeys([...byKey.keys()]).map((k) => `- [[Facts/Pending/${noteName(k)}|${label(k)}]]: ${label(byKey.get(k).text || "").slice(0, 200)}`) : ["_(none)_"]),
    "",
  ].join("\n");
}

// entities: visibleEntities().entities; types: entity-types.json;
// slugFor: key -> the name of its Views/Entities note.
function buildEntitiesIndex(entities = {}, types = {}, slugFor) {
  const aliases = {};
  for (const alias of Object.keys(types)) {
    let k = alias;
    for (const seen = new Set(); types[k]?.canonicalKey && !seen.has(k); ) {
      seen.add(k);
      k = types[k].canonicalKey;
    }
    if (k !== alias && entities[k]) (aliases[k] ||= []).push(label(alias));
  }
  const groups = new Map([...ENTITY_TYPES.filter((t) => TYPE_HEADINGS[t]), null].map((t) => [t, []]));
  for (const [key, e] of Object.entries(entities)) (groups.get(e.type) || groups.get(null)).push(key);
  const lines = ["# Entities Index", "", "Generated by Mana; edits here are overwritten.", ""];
  for (const [type, keys] of groups) {
    if (!keys.length) continue;
    lines.push(`## ${TYPE_HEADINGS[type] || "Unclassified"}`, "");
    for (const key of sortKeys(keys)) {
      const also = (aliases[key] || []).sort();
      lines.push(`- [[Views/Entities/${slugFor(key)}|${label(entities[key].display || key)}]]${also.length ? ` (also: ${also.join(", ")})` : ""}`);
    }
    lines.push("");
  }
  if (lines.length === 4) lines.push("_(none yet)_", "");
  return lines.join("\n");
}

module.exports = { FILLER, MIN_UNTYPED_MENTIONS, visibleEntities, buildFactsIndex, buildPendingReview, buildEntitiesIndex };
